#!/bin/bash

# Simple script for sending the approriate HTTP request to control the show
# Usage: 
#   ./showctrl <command>
#   <command> := start|stop|shutdown

curl -iX POST http://localhost:5000/$1